services:

  nuxt:
    build:
      context: ./nuxt
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    volumes:
      - ./nuxt:/app
      - /app/node_modules
    networks:
      - backend
    
  strapi:
    build:
      context: ./strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi123
      - DATABASE_SSL=false
    volumes:
      - ./strapi:/app
      - /app/node_modules
      - /app/public/uploads
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "90:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ./nuxt/.output/public:/var/www/nuxt
      - ./strapi/public/uploads:/var/www/strapi/uploads
    depends_on:
      - nuxt
      - strapi
    network:
      - backend

networks:
  backend
